#!/usr/bin/env bash
#
# Runs the rv32i_m/I subset of riscv-arch-test against this core.
#
# Prereqs (not installed by this script):
#   - riscv-none-elf (or similar) GCC/binutils toolchain, matching the
#     PREFIX used in Verification/Top Level Tests/Assembly Programs/Makefile
#   - Icarus Verilog (iverilog/vvp), same as run_tests.sh
#   - A clone of https://github.com/riscv/riscv-arch-test
#   - (optional but recommended) reference signatures generated by the
#     Sail RV32I model for the same tests, so results mean something
#     beyond "it halted". Without these you only get a sanity check that
#     each test ran to completion and produced *a* signature.
#
# Usage:
#   ./run_arch_tests.sh /path/to/riscv-arch-test [/path/to/ref_sigs]
#
# Exits 0 if every test ran to completion and (when references are given)
# every signature matched. Exits 1 otherwise.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"   # adjust if you place this dir elsewhere

ARCH_TEST_DIR="${1:?Usage: $0 /path/to/riscv-arch-test [/path/to/ref_sigs]}"
REF_SIG_DIR="${2:-}"

PREFIX="${PREFIX:-riscv-none-elf-}"
CC="${PREFIX}gcc"
OBJCOPY="${PREFIX}objcopy"
NM="${PREFIX}nm"

TEST_SRC_DIR="$ARCH_TEST_DIR/riscv-test-suite/rv32i_m/I/src"
ENV_DIR="$ARCH_TEST_DIR/riscv-test-suite/env"

WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

# --- Compile the simulation binary once, RTL + arch_test_tb -----------
mapfile -d '' RTL_SOURCES < <(
  {
    printf '%s\0' "$ROOT/RTL/riscv_pkg.sv"
    find "$ROOT/RTL" -mindepth 2 -name '*.sv' -print0 | sort -z
  }
)

SIM_BIN="$WORKDIR/arch_test_tb.vvp"
echo "Building simulation image..."
if ! iverilog -g2012 -o "$SIM_BIN" "${RTL_SOURCES[@]}" "$SCRIPT_DIR/arch_test_tb.sv" > "$WORKDIR/build.log" 2>&1; then
  echo "!! Failed to build simulation image:"
  cat "$WORKDIR/build.log"
  exit 1
fi

TOTAL=0
RAN_OK=0
MATCHED=0
MISMATCHED=0
NO_REF=0

for src in "$TEST_SRC_DIR"/*.S; do
  [ -e "$src" ] || continue
  name="$(basename "${src%.S}")"
  TOTAL=$((TOTAL + 1))
  echo "============================================================"
  echo " $name"
  echo "============================================================"

  elf="$WORKDIR/$name.elf"
  bin="$WORKDIR/$name.bin"
  hex="$WORKDIR/$name.hex"
  sig="$WORKDIR/$name.sig"

  if ! "$CC" -march=rv32i -mabi=ilp32 -static -mcmodel=medany \
        -nostdlib -nostartfiles \
        -I "$SCRIPT_DIR" -I "$ENV_DIR" \
        -T "$SCRIPT_DIR/link.ld" \
        -o "$elf" "$src" > "$WORKDIR/$name.compile.log" 2>&1; then
    echo "  !! COMPILE FAILED"
    cat "$WORKDIR/$name.compile.log"
    continue
  fi

  "$OBJCOPY" -O binary -j .text.init -j .text -j .data -j .signature.begin -j .signature -j .signature.end "$elf" "$bin"
  python3 "$ROOT/Verification/Top Level Tests/Assembly Programs/bin_to_hex.py" "$bin" "$hex" > /dev/null

  sigbegin="$("$NM" "$elf" | awk '$3=="begin_signature"{print $1}')"
  sigend="$("$NM" "$elf" | awk '$3=="end_signature"{print $1}')"

  if [ -z "$sigbegin" ] || [ -z "$sigend" ]; then
    echo "  !! Could not find begin_signature/end_signature symbols - skipping"
    continue
  fi

  # NOTE: vvp's process exit code does NOT reflect $finish(1) in the
  # testbench - it always exits 0. Pass/fail has to come from the
  # DONE:/FAIL: markers arch_test_tb.sv prints, same workaround
  # run_tests.sh already uses (it parses "N/M tests passed" text rather
  # than trusting the exit code).
  vvp "$SIM_BIN" \
      +HEXFILE="$hex" \
      +SIGFILE="$sig" \
      +SIGBEGIN="$sigbegin" \
      +SIGEND="$sigend" \
      > "$WORKDIR/$name.run.log" 2>&1

  cat "$WORKDIR/$name.run.log"

  if ! grep -q '^DONE:' "$WORKDIR/$name.run.log"; then
    echo "  !! SIMULATION FAILED / TIMED OUT"
    continue
  fi

  RAN_OK=$((RAN_OK + 1))

  if [ -n "$REF_SIG_DIR" ] && [ -f "$REF_SIG_DIR/$name.signature" ]; then
    if diff -q "$sig" "$REF_SIG_DIR/$name.signature" > /dev/null 2>&1; then
      echo "  -> SIGNATURE MATCH"
      MATCHED=$((MATCHED + 1))
    else
      echo "  !! SIGNATURE MISMATCH (see $sig vs $REF_SIG_DIR/$name.signature)"
      MISMATCHED=$((MISMATCHED + 1))
    fi
  else
    echo "  -> ran to completion, no reference signature to compare"
    NO_REF=$((NO_REF + 1))
  fi
done

echo "============================================================"
echo "Total tests found:   $TOTAL"
echo "Ran to completion:   $RAN_OK"
if [ -n "$REF_SIG_DIR" ]; then
  echo "Signature matches:   $MATCHED"
  echo "Signature mismatches:$MISMATCHED"
fi
echo "No reference sig:    $NO_REF"

if [ "$RAN_OK" -lt "$TOTAL" ] || [ "$MISMATCHED" -gt 0 ]; then
  echo "REGRESSION: FAILED"
  exit 1
fi

echo "REGRESSION: ALL AVAILABLE CHECKS PASSED"
exit 0
